import type { CertificatePermissionSettings } from "@/lib/server/certificate-permissions";
import type { AdminContent } from "@/lib/content-schema";
import {
  resolveCertificateAssetsForSlug,
  type ResolvedGlobalCertificateAssets,
} from "@/lib/global-certificate-assets";
import { resolveCertificateGeneratorApiUrl } from "@/lib/server/certificate-generator-api";

/** Production path: certificates are generated by the certificate generator API (lms-app-main/1). */
export function isCertificateApiProvider(perms: CertificatePermissionSettings): boolean {
  return perms.provider !== "builtin" && Boolean(resolveCertificateGeneratorApiUrl());
}

/** @deprecated Use isCertificateApiProvider */
export function isN8nCertificateProvider(perms: CertificatePermissionSettings): boolean {
  return isCertificateApiProvider(perms);
}

/**
 * Local PDF overlay when generator API is unavailable.
 */
export function mayUseLocalCertificateFallback(apiConfigured: boolean): boolean {
  const override = process.env.CERTIFICATE_LOCAL_FALLBACK?.trim().toLowerCase();
  if (override === "true") return true;
  if (override === "false") return false;
  return !apiConfigured;
}

export type CourseCertificateAssets = ResolvedGlobalCertificateAssets & {
  supplementaryDocs: { title: string; url: string }[];
};

export function resolveCourseCertificateAssets(
  content: AdminContent,
  courseSlug: string,
): CourseCertificateAssets {
  return resolveCertificateAssetsForSlug(content, courseSlug);
}

export function courseCertificateAssetsReady(assets: CourseCertificateAssets): boolean {
  return Boolean(assets.templateImage?.trim() && assets.badgeImage?.trim() && assets.transcriptFile?.trim());
}

export const COURSE_CERTIFICATE_ASSETS_MISSING_MESSAGE =
  "Upload certificate sample, badge, and transcript for this course (Course settings → Certificate), or set global defaults under Users & Access → Certificates.";

/** issuedVia values that indicate a full multi-page PDF from the generator API. */
export function isGeneratorIssuedVia(issuedVia: string): boolean {
  return issuedVia === "api" || issuedVia === "n8n";
}
